#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
RED="\e[31m"
YELLOW="\e[33m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

echo "Running pre-commit"
echo "Running format..."
format=$(npm run format)
if [[-n ${format}]]; then
    printf "${RED}something when wrong formating files:${ENDCOLOR}\n"
    echo "${format}"
    exit 1
fi

echo "Running lint..."
lint=$(npm run lint )
if [[-n ${format}]]; then
    printf "${RED}something when wrong running linter in files:${ENDCOLOR}\n"
    echo "${format}"
    exit 1
fi

echo "Running unit test..."
test=$(npm run test:unit)
if [[-n ${format}]]; then
    printf "${RED}something when wrong running unit test:${ENDCOLOR}\n"
    echo "${test}"
    exit 1
fi

git add -A .